# Generated by Django 5.0.1 on 2024-01-29 16:14

from django.db import migrations
from lantern_django import LanternExtension, LanternExtrasExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        LanternExtension(),
        LanternExtrasExtension(),
    ]
