# Generated by Django 5.0.1 on 2024-01-29 16:18

import django.contrib.postgres.fields
import lantern_django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=lantern_django.RealField(), null=True, size=3)),
            ],
            options={
                'indexes': [lantern_django.HnswIndex(dim=384, ef=64, ef_construction=64, fields=['embedding'], m=16, name='hnsw_idx', opclasses=['dist_l2sq_ops'])],
            },
        ),
    ]
