# Generated by Django 5.0.1 on 2024-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='company_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
