# Generated by Django 5.0.1 on 2024-01-29 19:46

import lantern_django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_item_city_item_company_name_item_country_item_state_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='hnsw_idx',
        ),
        migrations.AddIndex(
            model_name='item',
            index=lantern_django.HnswIndex(dim=384, ef=64, ef_construction=64, fields=['embedding'], m=16, name='hnsw_idx', opclasses=['dist_l2sq_ops']),
        ),
    ]
