name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.12, 3.8]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: python3 -m venv .venv && source .venv/bin/activate && python3 -m pip install -e ./lantern && python3 -m pip install -e ./lantern_pinecone