name: publish
on:
  workflow_dispatch:
    inputs:
      create_release:
        type: boolean
        description: "Create GitHub release for current version"
        required: false
        default: false
jobs:
  pypi-publish-lantern-client:
    name: Upload lantern-client to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lantern-client
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: cd lantern && python3 -m build && cd ..
      - name: Publish lantern-client package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: lantern/dist/
          skip-existing: true
  pypi-publish-lantern-pinecone-client:
    name: Upload lantern-pinecone to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lantern-pinecone
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: cd lantern_pinecone && python3 -m build && cd ..
      - name: Publish lantern-pinecone package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: lantern_pinecone/dist/
          skip-existing: true
